### ISSUE TITLE
поллы

### ISSUE THREAD

**Issue by rasputyashka** [lord-laminat/RtusskiBot#6]
Поллы работют и в вк и в телеге, можно пересылать их в оба чата.

**Comment by lord-laminat** [comment]
### Ошибка
В настоящий момент vkbottle ломается где-то в pydantic.
При попытке поймать сообщение, содержащее poll вызывается следующая ошибка:

```
Traceback (most recent call last):
  File "/home/rychkin/Documents/Projects/RtusskiBot/venv/lib/python3.12/site-packages/vkbottle/dispatch/base.py", line 24, in route
    await view.handle_event(event, ctx_api, self.state_dispenser)
  File "/home/rychkin/Documents/Projects/RtusskiBot/venv/lib/python3.12/site-packages/vkbottle/dispatch/views/abc/message.py", line 48, in handle_event
    message = await self.get_message(event, ctx_api, self.replace_mention)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rychkin/Documents/Projects/RtusskiBot/venv/lib/python3.12/site-packages/vkbottle/dispatch/views/bot/message.py", line 32, in get_message
    return message_min(event, ctx_api, replace_mention)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rychkin/Documents/Projects/RtusskiBot/venv/lib/python3.12/site-packages/vkbottle/tools/mini_types/bot/message.py", line 85, in message_min
    update = MessageNew(**event)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/rychkin/Documents/Projects/RtusskiBot/venv/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for MessageNew
object -> message -> attachments -> 0 -> poll -> anonymous
  value is not a valid dict (type=type_error.dict)
```

### Предположение о причине ошибки

В файле [vkbottle_types/codegen/objects.py](https://github.com/vkbottle/types/blob/195f0b73b7b4a907ac9bd57ab0e3019493ea12f6/vkbottle_types/codegen/objects.py) поле объекта [PollsPoll](https://github.com/vkbottle/types/blob/195f0b73b7b4a907ac9bd57ab0e3019493ea12f6/vkbottle_types/codegen/objects.py#L14368) тип поля `anonymous` указан как:
```python
anonymous: typing.Optional["PollsPollAnonymous"] = Field(
        default=None,
    )
    """Property `PollsPoll.anonymous`."""
```
а в ответе от сервера, в описании poll передается `boolean` значение. 
##### Пример:
```python
{'group_id': 227733132, 'type': 'message_new', 'event_id': '1a72208e5e6a0e7af270755c7f011bc10d8b51d8', 'v': '5.199', 'object': {'message': {'date': 1731592566, 'from_id': 566447608, 'id': 0, 'version': 10000005, 'out': 0, 'important': False, 'is_hidden': False, 'attachments': [{'type': 'poll', 'poll': {'multiple': False, 'end_date': 0, 'closed': False, 'is_board': False, 'can_edit': False, 'can_vote': False, 'can_report': False, 'can_share': False, 'created': 1731592564, 'id': 992644340, 'owner_id': 566447608, 'question': 'z', 'votes': 0, 'disable_unvote': False, 'anonymous': False, 'answer_ids': [], 'embed_hash': '992644340_012b8416a5486a9d67', 'answers': [{'id': 2642103871, 'rate': 0.0, 'text': 'z', 'votes': 0}], 'author_id': 566447608}}], 'conversation_message_id': 435, 'fwd_messages': [], 'text': '', 'is_unavailable': True, 'peer_id': 2000000001, 'random_id': 0}, 'client_info': {'button_actions': ['text', 'vkpay', 'open_app', 'location', 'open_link', 'open_photo', 'callback', 'intent_subscribe', 'intent_unsubscribe'], 'keyboard': True, 'inline_keyboard': True, 'carousel': True, 'lang_id': 0}}}
```
##### Гипотеза
`pydantic` роняет функцию ловли сообщения, так как обнаруживает несоответствие типов получаемого значения и ожидаемого.

**Comment by rasputyashka** [comment]
вполне возможно, что с апгрейдом на новую версию vk_bottle оно и починится, но там придется разбираться с ивент лупом, который vk_bottle больно странно использует. В общем, можешь как-нибудь позже взяться за это снова с идеей переписать на более новую версию.
